projects:
  AmplifyPhotosApi:
    schemaPath: amplify/backend/api/AmplifyPhotosApi/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
